sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t danielpineda/docker-react -f Dockerfile.dev . 
script:
    - docker run -e CI=true danielpineda/docker-react npm run test